// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CriptoDB.Migrations
{
    [DbContext(typeof(CryptoContext))]
    [Migration("20220105101229_MIgracionInicial")]
    partial class MIgracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Cripto.Models.Cartera", b =>
                {
                    b.Property<int>("CarteraId")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarteraId");

                    b.ToTable("Cartera");
                });

            modelBuilder.Entity("Cripto.Models.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CarteraId")
                        .HasColumnType("int");

                    b.Property<string>("MonedaId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContratoId");

                    b.HasIndex("CarteraId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("Cripto.Models.Moneda", b =>
                {
                    b.Property<string>("MonedaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Actual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Maximo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MonedaId");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("Cripto.Models.Contrato", b =>
                {
                    b.HasOne("Cripto.Models.Cartera", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("CarteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cripto.Models.Cartera", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
